# This workflow will do a clean install of Node dependencies and build the
# package across different versions of Node.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npx --package @angular/cli@^11 ng build @siren-js/ng
      - run: npx --package @angular/cli@^11 ng test @siren-js/ng
      - run: npx --package @angular/cli@^11 ng lint @siren-js/ng
      - run: npx codecov
